### ISSUE TITLE
Code Review for Jared

### ISSUE THREAD

**Issue by xseh** [AY2122S1-CS2113T-W13-1/tp#111]
For @jach23, 

1. Parser (line 338, 452, etc. ): Avoid naming shortcuts or make the meaning obvious (e.g. in a comment)
2. SearchItemCommand (line 59, etc. ): Avoid putting multiple statements on the same line

**Comment by JaCh23** [comment]
Hi XinRu, can I confirm whats the issue with Parser Lines 338 n 452? I only see white spacing errors

![image](https://user-images.githubusercontent.com/24263853/139912580-a5aed339-0c17-4ae9-a6cc-90bdd93f5659.png)

![image](https://user-images.githubusercontent.com/24263853/139912601-6a8b7cc0-77e3-488d-867c-308cf961a723.png)

**Comment by xseh** [comment]
My apologies, the lines may have moved, I was referring to the use of dayIdx and timeIdx as the variable names may not be clear or obvious. Perhaps consider dayIndex and timeIndex to make the naming clearer.
