### ISSUE TITLE
[PE-D] Edit trip 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-1/tp#124]
Editing the trip will add another end destination to the existing trip instead of changing the end destination of the trip. 
![image.png](https://raw.githubusercontent.com/deonchung/ped/main/files/4aff7602-8ef3-4be3-b7b8-9f4a2ff6cd44.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: deonchung/ped#4

**Comment by gavienwz** [comment]
Not bug
