### ISSUE TITLE
[PE-D] new trip

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-1/tp#145]
Should be trip name cannot be used instead or wrong format. 
![image.png](https://raw.githubusercontent.com/deonchung/ped/main/files/79b2f8cd-155a-41af-bc31-7311c37b7f03.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: deonchung/ped#7

**Comment by Uxinnn** [comment]
Hihi thanks for the review, can I just know how did u manage to input dat weird character in the first line of ur ss ah? so i can solve it thanks thanks :D
